trigger:
  branches:
    include:
      - main

pool:
  name: vmss-qkxbj8hg-azp

resources:
  repositories:
    - repository: templates
      type: git
      name: wiz-lab-ado-azure/templates

variables:
  - group: wiz-cli
  - name: IMAGE_NAME
    type: string
    value: my-django-app
  - name: IMAGE_REGISTRY
    type: string
    value: my-repository


stages: 
  - stage: build
    displayName: Docker build
    jobs:
      - job: buildACR
        displayName: Build container image to ACR
        steps:
          - task: DockerInstaller@0
            displayName: Install Docker CLI

          - task: Docker@2
            displayName: Build container image
            inputs:
              containerRegistry: $(IMAGE_REGISTRY)
              repository: $(IMAGE_REPOSITORY)
              command: build
              tags: $(Build.SourceVersion)

          - task: wiz@0
            displayName: Scan with Wiz
            inputs:
              command: 'image'
              clientid: $(WIZ_CLIENT_ID)
              secret: $(WIZ_CLIENT_SECRET)
              image: '$(IMAGE_REGISTRY)/$(IMAGE_NAME):$(Build.SourceVersion)'
              policyHitsOnly: true

          - task: Docker@2
            displayName: Push image to ACR
            inputs:
              containerRegistry: $(IMAGE_REGISTRY)
              repository: $(IMAGE_NAME)
              command: push
              tags: $(Build.SourceVersion)

#      - template: jfrog-docker@templates
#        parameters:
#          imageName: kcduboiswiz.jfrog.io/wizard-meeple/wizard-meeple

